# Generated by Django 5.1.3 on 2025-11-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
