# Generated by Django 5.1.3 on 2025-11-12 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_department_employee_department"),
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="geo.country",
            ),
        ),
    ]
