# Generated by Django 4.0.5 on 2022-06-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='code',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
