# Generated by Django 4.0.5 on 2022-07-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_control', '0002_employee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.TextField(default='pruebas'),
            preserve_default=False,
        ),
    ]
