# Generated by Django 4.0.5 on 2022-07-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_control', '0003_inventory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycount',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
