# Generated by Django 4.0.5 on 2022-07-12 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('inventory_control', '0004_inventorycount_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='employees.employee'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
