# Generated by Django 5.1.3 on 2025-11-06 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_control", "0006_inventory_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="description",
        ),
    ]
