# Generated by Django 5.1.3 on 2025-11-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_control", "0007_remove_inventory_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="inventory_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
