# Generated by Django 5.1.3 on 2025-11-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_control", "0008_inventory_inventory_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorycount",
            name="storage_position",
        ),
        migrations.AddField(
            model_name="inventorycount",
            name="position_letter",
            field=models.CharField(default="A", max_length=1),
        ),
    ]
