# Generated by Django 5.1.3 on 2025-11-06 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_control", "0009_remove_inventorycount_storage_position_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorycount",
            name="side",
        ),
        migrations.DeleteModel(
            name="Side",
        ),
    ]
