# Generated by Django 5.1.3 on 2025-11-06 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_control", "0010_remove_inventorycount_side_delete_side"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorycount",
            name="measurement_unit",
        ),
        migrations.RemoveField(
            model_name="inventorycount",
            name="entry_date",
        ),
        migrations.RemoveField(
            model_name="inventorycount",
            name="expiration_date",
        ),
        migrations.DeleteModel(
            name="MeasurementUnit",
        ),
    ]
