# Generated by Django 5.1.3 on 2025-11-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_control", "0011_remove_inventorycount_measurement_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorycount",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
