# Generated by Django 5.1.3 on 2025-11-12 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
        ("inventory_control", "0012_inventorycount_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventories",
                to="geo.country",
            ),
        ),
        migrations.AddField(
            model_name="inventorycount",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_counts",
                to="geo.country",
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouses",
                to="geo.country",
            ),
        ),
    ]
