# Generated by Django 5.1.3 on 2025-11-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_control", "0013_inventory_country_inventorycount_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorycount",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="inventory_counts/"
            ),
        ),
    ]
