# Generated by Django 4.0.5 on 2022-06-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
