# Generated by Django 4.0.5 on 2022-06-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='state',
            new_name='active',
        ),
    ]
