# Generated by Django 4.0.5 on 2022-07-07 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_state_product_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category__name',), 'verbose_name_plural': 'Productos'},
        ),
    ]
