# Generated by Django 5.1.3 on 2025-11-06 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="type",
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "Productos"},
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Type",
        ),
    ]
