# Generated by Django 5.1.3 on 2025-11-12 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
        ("products", "0007_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="brands",
                to="geo.country",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="geo.country",
            ),
        ),
    ]
